### ISSUE TITLE
Use of VIOs in the Performance_Tuning tutorial

### ISSUE THREAD

**Issue by ghost** [Xilinx/Vivado-Design-Tutorials#1]
Hello,

The _NoC_DDRMC/Performance_Tuning/_ tutorial has the following passage:

> To run the design in hardware, you will need to make some modifications. The Performance AXI TG has a feature whereby VIOs can be used to load instructions and read registers. [...]
> 
> Modifying the design is somewhat involved, so instead of walking through each step individually, a final design has been provided that runs on hardware.
> 

I was wondering if you have any references on how to use this AXI TG feature? In order to, for instance, test a different configuration of traffic generators on a vck board.

Thank you!

**Comment by imrickysu** [comment]
Please refer to AXI Traffic Generator User Guide https://www.xilinx.com/support/documentation/ip_documentation/perf_axi_tg/v1_0/pg381-perf-axi-tg-spec.pdf 

Chapter _Dynamic Operating Mode_ or search for keyword _VIO_
