### ISSUE TITLE
K means clustering user guide?

### ISSUE THREAD

**Issue by dj-park** [Xilinx/Vivado-Design-Tutorials#15]
https://github.com/Xilinx/Vivado-Design-Tutorials/tree/2021.1/Device_Architecture_Tutorials/Versal/NoC_DDRMC/04-NoC_Data_Movement_Comparison

It suggests me to take a look at ug1123 for further details on K means clustering, but I don't think there's user guide 1123. What's the correct reference?

**Comment by DavidDye** [comment]
This document was planned but never published, so the reference has been removed.
