### ISSUE TITLE
Implementation issue on Vivado 2021.2.1

### ISSUE THREAD

**Issue by ElMasto12** [Xilinx/Vivado-Design-Tutorials#22]
Hello, 

When I try the final design script on Vivado 2021.2.1 I sty stucked in Running opt_design for days. 
I change the tcl script to match my version of Vivado. 

![image](https://user-images.githubusercontent.com/78360974/166242085-f3027b3c-e20b-4a04-8992-16802b479acd.png)

Can someone help my please,

thank you

**Comment by DavidDye** [comment]
Which design are you running?  This information will tell us which owner will need to investigate.

**Comment by ElMasto12** [comment]
I worked on the finished design of the Performance Test of the Versal's NoC.

I finally found (more or less) my problem. In my company we work on Linux, when I launch a Konsole I used to put "csh" in order to start a C Shell (and implementation didn't work) and I tried to start with "BASH" and it works fine.

Thanks
