### ISSUE TITLE
GT_bd.tcl has a syntax error

### ISSUE THREAD

**Issue by marctylerb** [Xilinx/Vivado-Design-Tutorials#24]
A portion of the GT_bd.tcl needs to be commented to successfully run.

`source ./src_files/tcl_files/GT_bd.tcl
# \/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/
invalid command name "\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/"
    while executing
"\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/"
    (file "./src_files/tcl_files/GT_bd.tcl" line 16)`

**Comment by DavidDye** [comment]
Checked fix into local branches, waiting for other changes elsewhere to push live.
